### ISSUE TITLE
Could you tell me what software you use to the create the slides presented in "Blockchain - bitcoin.pdf"?

### ISSUE THREAD

**Issue by vangavroche** [tyrchen/unchained#1]
https://github.com/tyrchen/unchained/blob/master/Blockchain%20-%20bitcoin.pdf

I guess it acceptable to ask such question here (in the issue list). Tell me if I'm wrong.

**Comment by Clarence-pan** [comment]
I'm also going to ask the same question...

**Comment by tyrchen** [comment]
I'm using iPad pro + pen + Notability.

**Comment by vangavroche** [comment]
Thank you very much.
